
================== CRASH DETECTED ==================
Time: 2025-09-10 21:35:37
Runtime: 45.27 seconds
Exception Type: AttributeError
Exception Value: 'NoneType' object has no attribute 'get'

Traceback:
Traceback (most recent call last):
  File "c:\dcwidget\ui_main.py", line 710, in open_settings_window
    settings_dialog = SettingsWindow(self.data_manager, self.settings, None, pos=self._get_dialog_pos())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dcwidget\settings_window.py", line 101, in __init__
    self.rebuild_ui()
  File "c:\dcwidget\settings_window.py", line 589, in rebuild_ui
    self.update_account_status()
  File "c:\dcwidget\settings_window.py", line 595, in update_account_status
    self.account_status_label.setText(user_info.get('email', "정보 확인 불가")); self.account_button.setText("로그아웃")
                                      ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

================== END CRASH INFO ==================
